# Generated by Django 4.0.2 on 2022-02-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_from', models.CharField(default='', max_length=100, verbose_name='Qayerda')),
                ('is_to', models.CharField(default='', max_length=100, verbose_name='Qayerga')),
                ('date', models.CharField(default='', max_length=100, verbose_name='Qachon')),
                ('car', models.CharField(default='', max_length=100, verbose_name='Avtomobil')),
                ('telegram_id', models.BigIntegerField(default=1, verbose_name='Telegram ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100, verbose_name='Telefon')),
                ('comment', models.TextField(default='', verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='Telegram_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(default=1, verbose_name='Telegram ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Grux yoki Kanal nomi')),
            ],
            options={
                'verbose_name': 'Telegram group yoki kanal',
                'verbose_name_plural': 'Telegram group yoki kanallar',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Telegram ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('step', models.IntegerField(default=0)),
                ('is_from', models.CharField(default='', max_length=100, verbose_name='Qayerda')),
                ('is_to', models.CharField(default='', max_length=100, verbose_name='Qayerga')),
                ('date', models.CharField(default='', max_length=100, verbose_name='Qachon')),
                ('car', models.CharField(default='', max_length=100, verbose_name='Avtomobil')),
                ('phone', models.CharField(default='', max_length=100, verbose_name='Telefon')),
                ('comment', models.TextField(default='', verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
    ]
